# Generated by Django 2.0.7 on 2021-11-30 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='descriptipn',
            new_name='description',
        ),
    ]
